version: '3.9'

services:
  # name is optional for our mongodb
  my_mongodb_v1:
    # since mongo is an offical image we can use it.
    image: "mongo"

    # the port that we want to publish for mongodb
    ports:
      - "27017:27017"

    # our mongodb depends on volume to keep the data alive.
    volumes:
      - data:/data/db
    

  backend:
    # to build an image based on Dockerfile
    # it looks in this folder to find Dockerfile to build an image
    build: ./backend
    ports:

      - 3001:3001

    # depends_on means it will start our backend container once mongo-container is  up and running.
    depends_on:
      - my_mongodb_v1

  # name is optional for our frontend
  frontend:
    # to build an image based on Dockerfile
    # it looks in this folder to find Dockerfile to build an image
    build: ./

    # the port that we want to publish for frontend
    ports:
      - "3000:3000"
    # add bind mount volume to keep have updated source code
    environment:
      PORT: 3000

    depends_on:
      - backend

# declare the volumes name that our app is using.
volumes:
  data:
